### ISSUE TITLE
Is yaml supported really needed?

### ISSUE THREAD

**Issue by WtfJoke** [mbonig/state-machine#34]
What is the use case behind yaml support?

Asking because the template file exposed by the Step-Functions UI is JSON.

Because I am usually a bit picky about my dependencies and the used [js-yaml](https://github.com/nodeca/js-yaml) library doesn't seem to be maintained any more (no update since 3 years). 

So I personally would vote against yaml support, unless there is a specific use case.
If you want to support yaml it would be cool if you can replace `js-yaml` with the better maintained library called [yaml](https://www.npmjs.com/package/yaml)

(didn't want to come across as rude or similar, just curious 😄 )

**Comment by mbonig** [comment]
The use case was mostly "some people like yaml instead" and since CFN/SFN supported it, I wanted to support it in the construct as well.

As for js-yaml vs yaml, I used it because it was mature and I was fine with it being untouched in years. If there are functional issues with using it, please let me know what so I can address them and switch to something that will resolve those issues.
